-- NOVA STORE v1 database
-- Run this in Supabase SQL Editor after replacing nothing here.
-- After creating your own account, make yourself an admin by running:
-- update public.profiles set role = 'admin' where id = 'YOUR_AUTH_USER_ID';

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  email text,
  role text not null default 'customer' check (role in ('customer','admin')),
  created_at timestamptz not null default now()
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  description text default '',
  category text not null default 'Other',
  price numeric(12,2) not null default 0 check (price >= 0),
  image_url text default '',
  stock integer not null default 0 check (stock >= 0),
  featured boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  customer_name text not null,
  email text not null,
  total numeric(12,2) not null default 0 check (total >= 0),
  status text not null default 'Pending' check (status in ('Pending','Confirmed','Shipped','Delivered','Cancelled')),
  address text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  product_id bigint references public.products(id) on delete set null,
  product_name text not null,
  price numeric(12,2) not null default 0,
  quantity integer not null default 1 check (quantity > 0)
);

alter table public.profiles enable row level security;
alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;

-- Helper function for admin checks.
create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin'
  );
$$;

-- Profile policies
drop policy if exists "profiles own read" on public.profiles;
create policy "profiles own read" on public.profiles
for select to authenticated
using (id = auth.uid() or public.is_admin());

drop policy if exists "profiles own update" on public.profiles;
create policy "profiles own update" on public.profiles
for update to authenticated
using (id = auth.uid())
with check (id = auth.uid());

drop policy if exists "admins manage profiles" on public.profiles;
create policy "admins manage profiles" on public.profiles
for all to authenticated
using (public.is_admin())
with check (public.is_admin());

-- Product policies
drop policy if exists "products public read" on public.products;
create policy "products public read" on public.products
for select to anon, authenticated using (true);

drop policy if exists "admins manage products" on public.products;
create policy "admins manage products" on public.products
for all to authenticated
using (public.is_admin())
with check (public.is_admin());

-- Orders: customers see/create their own orders; admins manage all.
drop policy if exists "users read own orders" on public.orders;
create policy "users read own orders" on public.orders
for select to authenticated
using (user_id = auth.uid() or public.is_admin());

drop policy if exists "users create own orders" on public.orders;
create policy "users create own orders" on public.orders
for insert to authenticated
with check (user_id = auth.uid());

drop policy if exists "admins manage orders" on public.orders;
create policy "admins manage orders" on public.orders
for update to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "admins delete orders" on public.orders;
create policy "admins delete orders" on public.orders
for delete to authenticated
using (public.is_admin());

-- Order items follow the parent order.
drop policy if exists "users read own order items" on public.order_items;
create policy "users read own order items" on public.order_items
for select to authenticated
using (
  exists (
    select 1 from public.orders o
    where o.id = order_items.order_id
      and (o.user_id = auth.uid() or public.is_admin())
  )
);

drop policy if exists "users create own order items" on public.order_items;
create policy "users create own order items" on public.order_items
for insert to authenticated
with check (
  exists (
    select 1 from public.orders o
    where o.id = order_items.order_id
      and o.user_id = auth.uid()
  )
);

drop policy if exists "admins manage order items" on public.order_items;
create policy "admins manage order items" on public.order_items
for all to authenticated
using (public.is_admin())
with check (public.is_admin());

-- Automatically create a profile whenever a new auth user signs up.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, full_name, email)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'full_name', ''),
    new.email
  )
  on conflict (id) do update set
    full_name = excluded.full_name,
    email = excluded.email;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

-- Starter products
insert into public.products (name, description, category, price, image_url, stock, featured)
select * from (values
  ('Nova Smartphone','Fast everyday smartphone with a clean NOVA design.','Electronics',19999,'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=900&q=80',20,true),
  ('Wireless Headphones','Comfortable wireless headphones for music and study.','Electronics',2499,'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=900&q=80',35,true),
  ('Nova Smart Watch','Smart fitness and notification watch.','Accessories',3999,'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=900&q=80',18,true),
  ('Nova Laptop','Slim everyday laptop for coding, study and work.','Electronics',54999,'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=900&q=80',10,true),
  ('Classic Backpack','Simple backpack for school, travel and daily use.','Fashion',1499,'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=900&q=80',30,false),
  ('Desk Lamp','Compact LED desk lamp for a focused workspace.','Home',999,'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=900&q=80',25,false)
) as v(name,description,category,price,image_url,stock,featured)
where not exists (select 1 from public.products p where p.name = v.name);
